apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-transcriber
type: Opaque
data:
  {{- if .Values.transcriber.enabled }}
  JIGASI_TRANSCRIBER_USER: {{ .Values.transcriber.xmpp.user | b64enc }}
  JIGASI_TRANSCRIBER_PASSWORD: '{{ default (randAlphaNum 10) .Values.transcriber.xmpp.password | b64enc }}'
  {{- end }}

